---
- name: install nfs
  apt:
   name: nfs-kernel-server
   state: present
   install_recommends: false
   update_cache: true
   cache_valid_time: 300

- name: mkdir /var/nfs/general
  file:
   path: /var/nfs/general
   owner: nobody
   group: nogroup
   state: directory

- name: replace
  template: src=exports dest=/etc/exports backup=yes
  notify:
    - nfs-kernel-server restart
